import { MagicSchool, Incantation } from './types';

export const INITIAL_INCANTATIONS: Incantation[] = [
  {
    id: 'I-740921-A',
    code: 'G-14',
    school: MagicSchool.EVOCATION,
    section: '1.0',
    temporalMark: '21 SEP 1974',
    dateUnix: new Date('1974-09-21').getTime(),
    description:
      'Fireball detonation confirmed within optimal parameters. Primary mana surge recalibrated post-ignition to prevent thermal cascade.',
    status: 'normal',
    resonance: 74,
    deployments: 24,
    errorsFound: 0,
    coordinates: { x: 55, y: 72, label: 'Center Stage' },
    operator: 'A. Vance',
    pylonRef: 'Pylon-Alpha-01',
    harmonicIndex: 432,
  },
  {
    id: 'I-740928-D',
    code: 'G-18',
    school: MagicSchool.EVOCATION,
    section: '1.0',
    temporalMark: '28 SEP 1974',
    dateUnix: new Date('1974-09-28').getTime(),
    description:
      'Lightning arc stability test. Variance detected in grounding runes. Requires immediate structural review of primary pylons.',
    status: 'warning',
    resonance: 82,
    deployments: 12,
    errorsFound: 1,
    coordinates: { x: 30, y: 35, label: 'Left Balcony' },
    operator: 'E. Bradley',
    pylonRef: 'Pylon-Beta-02',
    harmonicIndex: 720,
  },
  {
    id: 'I-740921-B',
    code: 'G-15',
    school: MagicSchool.ABJURATION,
    section: '2.0',
    temporalMark: '21 SEP 1974',
    dateUnix: new Date('1974-09-21').getTime(),
    description:
      'Standard ward deployment around the perimeter. Kinetic barriers holding at 98% efficiency. No spatial anomalies reported.',
    status: 'normal',
    resonance: 92,
    deployments: 45,
    errorsFound: 0,
    coordinates: { x: 48, y: 88, label: 'Orchestra Pit' },
    operator: 'A. Vance',
    pylonRef: 'Pylon-Alpha-02',
    harmonicIndex: 110,
  },
  {
    id: 'I-740929-A',
    code: 'H-02',
    school: MagicSchool.ABJURATION,
    section: '2.0',
    temporalMark: '29 SEP 1974',
    dateUnix: new Date('1974-09-29').getTime(),
    description:
      'Anti-scrying matrix initiated. Flux saturation nominal. Aetheric signature masked successfully from external observation.',
    status: 'normal',
    resonance: 68,
    deployments: 18,
    errorsFound: 0,
    coordinates: { x: 80, y: 22, label: 'Sound Booth' },
    operator: 'H. Ginzberg',
    pylonRef: 'Pylon-Gamma-03',
    harmonicIndex: 440,
  },
  {
    id: 'I-740922-A',
    code: 'P-03',
    school: MagicSchool.CONJURATION,
    section: '3.0',
    temporalMark: '22 SEP 1974',
    dateUnix: new Date('1974-09-22').getTime(),
    description:
      'Signal Lost - Counterspell Feedback Loop Detected. Breach in sector containment. Immediate quarantine recommended.',
    status: 'error',
    resonance: 15,
    deployments: 5,
    errorsFound: 8,
    coordinates: { x: 50, y: 55, label: 'Main Seating Row F' },
    operator: 'E. Bradley',
    pylonRef: 'Pylon-Delta-01',
    harmonicIndex: 880,
  },
  {
    id: 'I-740930-B',
    code: 'P-05',
    school: MagicSchool.CONJURATION,
    section: '3.0',
    temporalMark: '30 SEP 1974',
    dateUnix: new Date('1974-09-30').getTime(),
    description:
      'Minor elemental sprite summoned for ventilation maintenance. Binding circles intact. Entity compliance confirmed.',
    status: 'normal',
    resonance: 54,
    deployments: 32,
    errorsFound: 0,
    coordinates: { x: 18, y: 45, label: 'Air Exhaust Plenums' },
    operator: 'A. Vance',
    pylonRef: 'Pylon-Alpha-04',
    harmonicIndex: 250,
  },
  {
    id: 'I-740923-A',
    code: 'O-112',
    school: MagicSchool.TRANSMUTATION,
    section: '4.0',
    temporalMark: '23 SEP 1974',
    dateUnix: new Date('1974-09-23').getTime(),
    description:
      'Lead-to-gold catalytic conversion sequence tested. Mana surge in Sector O exceeding 1970 baseline. Isotope decay accelerated.',
    status: 'normal',
    resonance: 89,
    deployments: 6,
    errorsFound: 0,
    coordinates: { x: 70, y: 40, label: 'Right Balcony' },
    operator: 'M. Curie-Retro',
    pylonRef: 'Pylon-Epsilon-01',
    harmonicIndex: 984,
  },
  {
    id: 'I-740924-C',
    code: 'B-22',
    school: MagicSchool.DIVINATION,
    section: '5.0',
    temporalMark: '24 SEP 1974',
    dateUnix: new Date('1974-09-24').getTime(),
    description:
      'Long-range scrying session targeting the northern ley lines. Visuals confirmed. Chrono-distortion minimal. Session closed and archived.',
    status: 'normal',
    resonance: 62,
    deployments: 14,
    errorsFound: 0,
    coordinates: { x: 50, y: 15, label: 'Projection Box' },
    operator: 'H. Ginzberg',
    pylonRef: 'Pylon-Gamma-01',
    harmonicIndex: 120,
  },
  {
    id: 'I-740925-A',
    code: 'M-41',
    school: MagicSchool.ENCHANTMENT,
    section: '6.0',
    temporalMark: '25 SEP 1974',
    dateUnix: new Date('1974-09-25').getTime(),
    description:
      'Aetheric relay network synchronized with central crystalline hub. Cognitive enhancement aura distributed across engineering deck.',
    status: 'normal',
    resonance: 45,
    deployments: 9,
    errorsFound: 0,
    coordinates: { x: 35, y: 75, label: 'Backstage Under-Deck' },
    operator: 'M. Tavern-Keeper',
    pylonRef: 'Pylon-Sigma-02',
    harmonicIndex: 60,
  },
  // Extra pages of items for dense pagination (adding 12 more archival logs)
  {
    id: 'I-741002-C',
    code: 'G-22',
    school: MagicSchool.EVOCATION,
    section: '1.0',
    temporalMark: '02 OCT 1974',
    dateUnix: new Date('1974-10-02').getTime(),
    description:
      'Thermal combustion array calibration. Unstable blue flame stabilized with local gravity inhibitors. Heat output exceeded expectations.',
    status: 'normal',
    resonance: 94,
    deployments: 11,
    errorsFound: 0,
    coordinates: { x: 58, y: 70, label: 'Center Stage Behind Curtain' },
    operator: 'A. Vance',
    pylonRef: 'Pylon-Alpha-01',
    harmonicIndex: 512,
  },
  {
    id: 'I-741005-B',
    code: 'K-09',
    school: MagicSchool.ABJURATION,
    section: '2.0',
    temporalMark: '05 OCT 1974',
    dateUnix: new Date('1974-10-05').getTime(),
    description:
      'Acoustic silencing dampener tested around the Orchestra pit. Complete audio insulation achieved for 45 minutes till rune decay.',
    status: 'normal',
    resonance: 79,
    deployments: 8,
    errorsFound: 0,
    coordinates: { x: 45, y: 80, label: 'Orchestra Left Side' },
    operator: 'H. Ginzberg',
    pylonRef: 'Pylon-Beta-05',
    harmonicIndex: 16,
  },
  {
    id: 'I-741009-F',
    code: 'P-12',
    school: MagicSchool.CONJURATION,
    section: '3.0',
    temporalMark: '09 OCT 1974',
    dateUnix: new Date('1974-10-09').getTime(),
    description:
      'Rift dilatation anomaly. Minor spectral vortex formed behind stage elevator. Secondary sealing circle deployed successfully.',
    status: 'warning',
    resonance: 38,
    deployments: 4,
    errorsFound: 2,
    coordinates: { x: 30, y: 85, label: 'Understage Lift Mechanism' },
    operator: 'E. Bradley',
    pylonRef: 'Pylon-Delta-03',
    harmonicIndex: 1110,
  },
  {
    id: 'I-741014-X',
    code: 'O-210',
    school: MagicSchool.TRANSMUTATION,
    section: '4.0',
    temporalMark: '14 OCT 1974',
    dateUnix: new Date('1974-10-14').getTime(),
    description:
      'Gravity inversion test in the VIP lounge. Glassware and furniture floated without structural damage. Recalibrator overheated.',
    status: 'warning',
    resonance: 71,
    deployments: 3,
    errorsFound: 1,
    coordinates: { x: 65, y: 25, label: 'VIP Balcony Box' },
    operator: 'M. Curie-Retro',
    pylonRef: 'Pylon-Epsilon-04',
    harmonicIndex: 300,
  },
  {
    id: 'I-741018-D',
    code: 'B-49',
    school: MagicSchool.DIVINATION,
    section: '5.0',
    temporalMark: '18 OCT 1974',
    dateUnix: new Date('1974-10-18').getTime(),
    description:
      'Temporal window simulation. Observed events from year 2026. Cryptic records indicate server systems run entirely in containers. Highly speculative description dismissed.',
    status: 'normal',
    resonance: 50,
    deployments: 2,
    errorsFound: 0,
    coordinates: { x: 50, y: 15, label: 'Projection Box' },
    operator: 'E. Bradley',
    pylonRef: 'Pylon-Gamma-04',
    harmonicIndex: 999,
  },
  {
    id: 'I-741022-A',
    code: 'M-48',
    school: MagicSchool.ENCHANTMENT,
    section: '6.0',
    temporalMark: '22 OCT 1974',
    dateUnix: new Date('1974-10-22').getTime(),
    description:
      'Subconscious suggestion array tests. Audience seating calibrated to increase emotional alignment with performance. Strong feedback peaks observed.',
    status: 'normal',
    resonance: 83,
    deployments: 14,
    errorsFound: 0,
    coordinates: { x: 50, y: 50, label: 'Seating Row L' },
    operator: 'M. Tavern-Keeper',
    pylonRef: 'Pylon-Sigma-01',
    harmonicIndex: 88,
  },
  {
    id: 'I-741029-E',
    code: 'G-19',
    school: MagicSchool.EVOCATION,
    section: '1.0',
    temporalMark: '29 OCT 1974',
    dateUnix: new Date('1974-10-29').getTime(),
    description:
      'Mana burst overload test. Safe detonation breached stage barrier. High heat dispersion detected nearby. Core shut down initiated manually.',
    status: 'error',
    resonance: 95,
    deployments: 22,
    errorsFound: 5,
    coordinates: { x: 52, y: 68, label: 'Main Stage center' },
    operator: 'A. Vance',
    pylonRef: 'Pylon-Alpha-01',
    harmonicIndex: 1200,
  },
  {
    id: 'I-741103-W',
    code: 'K-12',
    school: MagicSchool.ABJURATION,
    section: '2.0',
    temporalMark: '03 NOV 1974',
    dateUnix: new Date('1974-11-03').getTime(),
    description:
      'Resonating shield alignment failure. Dampener coil collapsed, causing standard lightning arcs to cross-couple with background scrying array.',
    status: 'error',
    resonance: 8,
    deployments: 1,
    errorsFound: 9,
    coordinates: { x: 42, y: 38, label: 'Balcony Left Pillar' },
    operator: 'E. Bradley',
    pylonRef: 'Pylon-Beta-01',
    harmonicIndex: 1540,
  },
  {
    id: 'I-741107-Z',
    code: 'P-18',
    school: MagicSchool.CONJURATION,
    section: '3.0',
    temporalMark: '07 NOV 1974',
    dateUnix: new Date('1974-11-07').getTime(),
    description:
      'Spatial fissure containment loop. Portal successfully stabilized to allow pure water condensation retrieval. Zero anomalous spikes recorded.',
    status: 'normal',
    resonance: 67,
    deployments: 7,
    errorsFound: 0,
    coordinates: { x: 25, y: 60, label: 'Stage Dressing Rooms' },
    operator: 'A. Vance',
    pylonRef: 'Pylon-Alpha-05',
    harmonicIndex: 330,
  },
];
